media:
  input: content/assets
  output: /assets

content:
  - name: posts
    label: Posts
    type: collection
    path: content/posts
    filename: "{year}-{month}-{day}-{title}.md"
    view:
      fields: [title, created, tags]
      primary: title
      sort: [created, title]
      default:
        sort: created
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        description: A short summary used on social media and by search engines.
      - name: created
        label: Published
        type: date
        options:
          time: true
      - name: modified
        label: Last updated
        type: date
        options:
          time: true
      - name: tags
        label: Tags
        type: string
        description: "Comma-separated, like: Personal, Politics, Technology"
      - name: template
        type: string
        hidden: true
        default: post.html
      - name: uuid
        label: UUID
        type: uuid
      - name: body
        label: Post
        type: rich-text
        options:
          format: markdown
          switcher: false
          path: posts
          rename: true
          extensions: [jpg, jpeg, png, gif, webp]

  - name: home
    label: Home page
    type: file
    path: content/home.md
    fields:
      - { name: title, type: string }
      - { name: description, type: text }
      - { name: body, label: Page content, type: rich-text }
  - name: about
    label: About page
    type: file
    path: content/about.md
    fields:
      - { name: title, type: string }
      - { name: description, type: text }
      - { name: body, label: Page content, type: rich-text }
  - name: now
    label: Now page
    type: file
    path: content/now.md
    fields:
      - { name: title, type: string }
      - { name: description, type: text }
      - { name: body, label: Page content, type: rich-text }
  - name: colophon
    label: Colophon
    type: file
    path: content/colophon.md
    fields:
      - { name: title, type: string }
      - { name: description, type: text }
      - { name: body, label: Page content, type: rich-text }

settings:
  content:
    merge: direct
