<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:a="http://www.w3.org/2005/Atom"
	exclude-result-prefixes="a">
	<xsl:output method="html" encoding="UTF-8"/>
	<xsl:template match="/">
		<html>
			<head>
				<meta charset="utf-8" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<title><xsl:value-of select="a:feed/a:title"/></title>
				<style>
					:root {
						color-scheme: light dark;
					}
					body {
						font-family: system-ui, sans-serif;
						padding: 1em;
					}
					main {
						max-width: 64ch;
						margin: auto;
					}
					h1 {
						margin-bottom: 0.5em;
					}
					p {
						line-height: 1.4;
					}
					.entry {
						margin-bottom: 1.5em;
						border-top: 1px dotted currentColor;
					}
					.notice {
						display: inline-block;
						background: color-mix(in srgb, currentColor 10%, transparent);
						padding: 1em;
						opacity: 0.7;
						border-radius: .3em;
						margin: 1em -0.5em 1em -0.5em;
					}
					footer {
						border-top: 1px dotted currentColor;
						padding-top: 1rem;
					}
					@view-transition {
						navigation: auto;
					}
				</style>
			</head>
			<body>
				<main>
					<div class="notice">This is an Atom feed generated by the Atom Power-Up for <a href="https://www.neato.pub">Neato</a>. You can subscribe to it using a feed reader, and you’ll always see the latest stuff there. If you're reading this in your browser, that’s cool too. But feeds work great with feed readers!</div>
					<h1><xsl:value-of select="a:feed/a:title"/></h1>
					<xsl:for-each select="a:feed/a:entry">
						<div class="entry">
							<h2>
								<xsl:choose>
									<xsl:when test="a:link">
										<a href="{a:link/@href}">
											<xsl:value-of select="a:title"/>
										</a>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="a:title"/>
									</xsl:otherwise>
								</xsl:choose>
							</h2>
							<p class="published-date">
								Published: <xsl:value-of select="a:published"/>
								<xsl:if test="a:updated and a:updated != a:published">
										<br/>Updated: <xsl:value-of select="a:updated"/>
								</xsl:if>
							</p>
							<xsl:copy-of select="a:content/*"/>
						</div>
					</xsl:for-each>
					<footer><nav><a href="/home">Home</a></nav></footer>
				</main>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
